import type { IPlatformConfig } from "@/types";

export const DEFAULT_CONFIG: IPlatformConfig = {
  name: "CreLab",
  tagline: "Get hired for your creativity, not your follower count.",
  primaryColor: "#E8FF47",
  feeRate: 0.05,
  escrowReleaseDays: 5,
  cancellationPolicy: {
    fullRefundThresholdHours: 48,
    lateCancellationHoldPercent: 50,
  },
  categories: [
    {
      slug: "content-creator",
      label: "Content Creator",
      description: "UGC, lifestyle, brand content, social media",
      icon: "video",
      active: true,
      fieldSchema: [
        {
          key: "bio",
          label: "Bio",
          type: "text",
          required: true,
          placeholder: "Tell brands what makes you unique...",
        },
        {
          key: "location",
          label: "Location",
          type: "text",
          required: true,
          placeholder: "e.g. Lagos, Nigeria",
        },
        {
          key: "yearsActive",
          label: "Years Active",
          type: "number",
          required: true,
          placeholder: "e.g. 3",
        },
        {
          key: "experienceLevel",
          label: "Experience Level",
          type: "select",
          required: true,
          options: ["EMERGING", "ESTABLISHED", "VETERAN"],
        },
        {
          key: "nicheTags",
          label: "Content Niche",
          type: "tags",
          required: true,
          placeholder: "Type and enter...",
        },
        {
          key: "activePlatforms",
          label: "Active Platforms",
          type: "tags",
          required: true,
          placeholder: "Type and enter...",
        },
      ],
    },
    {
      slug: "cinematographer",
      label: "Cinematographer / Videographer",
      description: "Events, commercials, narrative, documentary",
      icon: "camera",
      active: true,
      fieldSchema: [
        {
          key: "bio",
          label: "Bio",
          type: "text",
          required: true,
          placeholder: "Tell brands what makes you unique...",
        },
        {
          key: "location",
          label: "Location",
          type: "text",
          required: true,
          placeholder: "e.g. Lagos, Nigeria",
        },
        {
          key: "yearsActive",
          label: "Years Active",
          type: "number",
          required: true,
          placeholder: "e.g. 3",
        },
        {
          key: "experienceLevel",
          label: "Experience Level",
          type: "select",
          required: true,
          options: ["EMERGING", "ESTABLISHED", "VETERAN"],
        },
        {
          key: "equipment",
          label: "Equipment",
          type: "tags",
          required: true,
          placeholder: "e.g. Sony A7S III, DJI RS3...",
        },
        {
          key: "shootingStyle",
          label: "Shooting Style",
          type: "tags",
          required: true,
          placeholder: "e.g. Documentary, Cinematic...",
        },
        {
          key: "coverageType",
          label: "Coverage Type",
          type: "select",
          required: true,
          options: ["EVENTS", "COMMERCIAL", "NARRATIVE", "DOCUMENTARY"],
        },
      ],
    },
  ],
  features: {
    guestBrowse: true,
    googleDriveSync: true,
    blogEnabled: true,
  },
};
